# Generated by Django 4.0.4 on 2022-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
