# Generated by Django 4.0.4 on 2022-04-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_body_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_post',
            new_name='parent',
        ),
    ]
