# Generated by Django 4.0.4 on 2022-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_like_author_like_author_like_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
