# Generated by Django 4.0.4 on 2022-04-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
