# Generated by Django 4.0.4 on 2022-04-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_like_like_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
