# Generated by Django 4.0.4 on 2022-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_id',
            field=models.IntegerField(default=1),
        ),
    ]
